// REFLEXA v3.0 — Client-Side License Validator
// Validates keys generated by the Cloudflare Worker
// The secret here is obfuscated in production build — never plain text in dist/

function enc(s) { return new TextEncoder().encode(s); }

// Secret derived in multiple steps to resist static analysis
// After obfuscation: this becomes unreadable
function _S() {
  const a = ['5K', 'CR', '_2', 'X3', 'RF'];
  const b = ['0_', 'ET', 'LX', 'S_'];
  const c = [a[4], a[1], b[1], b[2], a[0], b[3], a[3], b[0]];
  return c.join('').split('').map((ch, i) => String.fromCharCode(ch.charCodeAt(0) ^ (i % 7))).join('');
}

async function hmacHex(data, secret) {
  const key = await crypto.subtle.importKey(
    'raw', enc(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false, ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, enc(data));
  return Array.from(new Uint8Array(sig)).map(b => b.toString(16).padStart(2, '0')).join('');
}

function constantEq(a, b) {
  if (a.length !== b.length) return false;
  let r = 0;
  for (let i = 0; i < a.length; i++) r |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return r === 0;
}

export const license = {
  // Full cryptographic validation (same algorithm as Worker keygen.js)
  async validate(key) {
    if (!key) return { valid: false, reason: 'No key' };
    const clean = key.trim().toUpperCase().replace(/\s/g, '');

    if (!clean.startsWith('RXFLX-')) return { valid: false, reason: 'Invalid prefix' };

    const parts = clean.slice(6).split('-');
    if (parts.length !== 4) return { valid: false, reason: 'Invalid format' };

    const [expiry, eHash, features, checksum] = parts;
    const payload  = `${expiry}-${eHash}-${features}`;
    const expected = (await hmacHex(payload, _S())).slice(0, 8).toUpperCase();

    if (!constantEq(checksum, expected)) return { valid: false, reason: 'Invalid signature' };

    const expiryMs = parseInt(expiry, 36);
    if (isNaN(expiryMs) || Date.now() > expiryMs)
      return { valid: false, reason: 'Key expired' };

    const featureBits = parseInt(features, 36);
    return {
      valid: true,
      expiry: new Date(expiryMs).toLocaleDateString(),
      features: {
        unlimited:  !!(featureBits & 1),
        export:     !!(featureBits & 2),
        history30:  !!(featureBits & 4),
        advanced:   !!(featureBits & 8),
        enterprise: !!(featureBits & 16),
      },
    };
  },

  // Legacy v2.x key support (simple pattern — for existing customers)
  isLegacyKey(key) {
    return /^REFLEXA-PRO-[A-Z0-9]{4}-[A-Z0-9]{4}$/i.test(key.trim());
  },

  // Quick format check for UI (before async validation)
  looksValid(key) {
    return /^RXFLX-[A-Z0-9]{5,}-[A-Z0-9]{4,6}-[A-Z0-9]{1,3}-[A-Z0-9]{8}$/i.test(key.trim());
  },
};
